import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          // 'Login': 'Login',
          // 'Enter your User Name': 'Enter your User Name',
          // 'Enter your Password': 'Enter your Password',
          // 'Language Preference': 'Language Preference',
          // 'Search': 'Search',
          // 'No tasks available': 'No tasks available',
          // 'Create New Task': 'Create New Task',
          // 'Enter task name': 'Enter task name',
          // 'Priority': 'Priority',
          // 'High': 'High',
          // 'Medium': 'Medium',
          // 'Low': 'Low',
          // 'Select Date': 'Select Date',
          // 'No date selected': 'No date selected',
          // 'Select Time': 'Select Time',
          // 'No time selected': 'No time selected',
          // 'Enter the description': 'Enter the description',
          // 'Save': 'Save',
          // 'Cancel': 'Cancel',
          // 'Profile': 'Profile',
          // 'Settings': 'Settings',
          // 'Privacy Policy': 'Privacy Policy',
          // 'About': 'About',
          // 'Logro App': 'Logro App',
          // 'Username': 'Username',
          // 'New Password': 'New Password',
          // 'Confirm Password': 'Confirm Password',
          // 'Save Changes': 'Save Changes',
          // 'Logout': 'Logout',
        },
        'ml': {
          'Login': 'ലോഗിൻ',
          'Enter your User Name': 'നിങ്ങളുടെ യൂസർനെയിം നൽകുക',
          'Enter your Password': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
          'Language Preference': 'ഭാഷാ മുൻഗണന',
          'Search': 'സേർച്ച് ',
          'No tasks available': 'ടാസ്കുകൾ ലഭ്യമായില്ല',
          'Create New Task': 'പുതിയ ടാസ്ക് സൃഷ്‌ടിക്കുക',
          'Enter task name': 'ടാസ്ക് നാമം നൽകുക',
          'Priority': 'പ്രാമുഖ്യം',
          'High': 'ഉയരം',
          'Medium': 'മധ്യം',
          'Low': 'താഴം',
          'Select Date': 'തീയതി തിരഞ്ഞെടുക്കുക',
          'No date selected': 'തീയതി തിരഞ്ഞെടുക്കപ്പെട്ടിട്ടില്ല',
          'Select Time': 'സമയം തിരഞ്ഞെടുക്കുക',
          'No time selected': 'സമയം തിരഞ്ഞെടുക്കപ്പെട്ടിട്ടില്ല',
          'Enter the description': 'വിവരണം നൽകുക',
          'Save': 'സേവ്',
          'Cancel': 'റദ്ദാക്കുക',
          'Profile': 'പ്രൊഫൈൽ',
          'Settings': 'സജ്ജീകരണങ്ങൾ',
          'Privacy Policy': 'പ്രൈവസി പോളിസി',
          'About': 'എബൌട്ട് ',
          'Logro App': 'ലോഗ്രോ ആപ്പ്',
          'Username': 'പുതിയ ഉപയോക്തൃനാമം',
          'New Password': 'പുതിയ പാസ്‌വേഡ്',
          'Confirm Password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
          'Save Changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
          'Logout': 'ലോഗ് ഔട്ട്',
          'Edit Task': 'ടാസ്‌ക് തിരുത്തുക',
          'Task Name': 'ടാസ്‌ക് നാമം',
          'Description': 'വിവരണം',
          'Date': 'തീയതി',
          'Time': 'സമയം',
          'No date set': 'തീയതി സജ്ജീകരിച്ചിട്ടില്ല',
          'No time set': 'സമയം സജ്ജീകരിച്ചിട്ടില്ല',
        },
      };
}
